#!/bin/bash

TRAIN_DIR="~/tensorflow/data/dataset-resized/"
VALIDATION_DIR=$TRAIN_DIR
OUTPUT_DIRECTORY="~/tensorflow/data/out/"
LABELS_FILE="~/tensorflow/data/labels.txt"


# build the preprocessing script.
cd tensorflow-models/inception
bazel build //inception:build_image_data

# convert the data.
bazel-bin/inception/build_image_data \
  --train_directory="${TRAIN_DIR}" \
  --validation_directory="${VALIDATION_DIR}" \
  --output_directory="${OUTPUT_DIRECTORY}" \
  --labels_file="${LABELS_FILE}" \
  --train_shards=128 \
  --validation_shards=24 \
  --num_threads=8
